# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: |
          flutter pub get
          dart pub add --dev test

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
